### PR TITLE
K8SPG-38 Clone cluster test

### PR DESCRIPTION
**Pull request by cap1984**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | failed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| clone-cluster | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/85/commits/5cb024f68f1afd2e0c435ac43d69f98daf650192
image: `perconalab/percona-postgresql-operator:PR-85-5cb024f6-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-85-5cb024f6-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-85-5cb024f6-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-85-5cb024f6-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-85-5cb024f6-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-85-5cb024f6-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-postgresql-operator/pull/85/commits/62dd8167c615020c523cd2bbd7fae2439b3ee24c
image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-postgresql-operator/pull/85/commits/62dd8167c615020c523cd2bbd7fae2439b3ee24c
image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-postgresql-operator/pull/85/commits/62dd8167c615020c523cd2bbd7fae2439b3ee24c
image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-postgresql-operator/pull/85/commits/62dd8167c615020c523cd2bbd7fae2439b3ee24c
image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-85-62dd8167-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| clone-cluster | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/85/commits/938aabdd28b72a94c757352aa8b5f12cb2ad2fd7
image: `perconalab/percona-postgresql-operator:PR-85-938aabdd-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-85-938aabdd-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-85-938aabdd-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-85-938aabdd-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-85-938aabdd-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-85-938aabdd-pgo-deployer`

**Review by hors — APPROVED** [review]

**Pull request merged**
