### PR TITLE
K8SPG-188 added loadBalancerIP field to pgPrimary and pgBouncer

### PR DESCRIPTION
**Pull request by eightseventhreethree**
Added loadBalancerIP field to pgPrimary and pgBouncer, but not pgReplicas per request in ticket: K8SPG-188

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/version-service.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/init-deploy.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/scheduled-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/upgrade.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/demand-backup.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0502bde0/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/299/commits/0502bde010a01cf6aa64f851f6cbc822268cde66
image: `perconalab/percona-postgresql-operator:PR-299-0502bde0-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-299-0502bde0-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-299-0502bde0-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-299-0502bde0-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-299-0502bde0-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-299-0502bde0-pgo-deployer`

**Comment by spron-in** [comment]
@eightseventhreethree thank you for the contribution! We are going to review it, but it looks pretty straight forward. 
We will need to update the docs as well.
Do you have any practical use case in mind for this?

**Comment by eightseventhreethree** [comment]
> @eightseventhreethree thank you for the contribution! We are going to review it, but it looks pretty straight forward. We will need to update the docs as well. Do you have any practical use case in mind for this?

Nope, I was just answering the call out that Peter made on LinkedIn to contribute and I found the Jira ticket. 

https://percona.community/contribute/help-wanted/

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/demand-backup.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/init-deploy.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/scheduled-backup.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/version-service.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0e1f0e30/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/299/commits/0e1f0e30d0dc01ce826799aa68a49358c1f81d07
image: `perconalab/percona-postgresql-operator:PR-299-0e1f0e30-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-299-0e1f0e30-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-299-0e1f0e30-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-299-0e1f0e30-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-299-0e1f0e30-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-299-0e1f0e30-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/upgrade.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/scheduled-backup.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/init-deploy.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/recreate.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/version-service.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/affinity.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/demand-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/ns-mode.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ea17746a/smart-update.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/299/commits/ea17746a89005c9d43a1a1b222f3182ef340b7be
image: `perconalab/percona-postgresql-operator:PR-299-ea17746a-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-299-ea17746a-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-299-ea17746a-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-299-ea17746a-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-299-ea17746a-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-299-ea17746a-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/scheduled-backup.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/init-deploy.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/version-service.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/faec5fee/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/299/commits/faec5feee9512aab8d60f6cbacdf6fdc8c2a723a
image: `perconalab/percona-postgresql-operator:PR-299-faec5fee-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-299-faec5fee-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-299-faec5fee-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-299-faec5fee-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-299-faec5fee-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-299-faec5fee-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/scheduled-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/upgrade.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/init-deploy.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/version-service.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/ce3afd1e/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/299/commits/ce3afd1eb3c79b676cd7f35573c0cc32b6e320d5
image: `perconalab/percona-postgresql-operator:PR-299-ce3afd1e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-299-ce3afd1e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-299-ce3afd1e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-299-ce3afd1e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-299-ce3afd1e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-299-ce3afd1e-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/init-deploy.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/upgrade.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/scheduled-backup.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/version-service.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/demand-backup.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-299/0b165b5d/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/299/commits/0b165b5d5209ad2437d26eeefe6f9b98ffccc2ca
image: `perconalab/percona-postgresql-operator:PR-299-0b165b5d-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-299-0b165b5d-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-299-0b165b5d-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-299-0b165b5d-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-299-0b165b5d-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-299-0b165b5d-pgo-deployer`

**Comment by Aleksa-del** [comment]
Hello, @eightseventhreethree ! Thank you for your contributions! We would like to send you a gift from Percona. Please, contact us at community-team@percona.com.

**Pull request merged**
