### PR TITLE
CLOUD-685 fix monitoring test

### PR DESCRIPTION
**Pull request by nmarukovich**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/demand-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/scaling.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/version-service.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/affinity.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/scheduled-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/7ecee5a9/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/213/commits/7ecee5a94f6e314af7e43eece6ae5f288856a23e
image: `perconalab/percona-postgresql-operator:PR-213-7ecee5a9-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-213-7ecee5a9-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-213-7ecee5a9-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-213-7ecee5a9-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-213-7ecee5a9-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-213-7ecee5a9-pgo-deployer`

**Comment by hors** [comment]
@nmarukovich please add task number

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/init-deploy.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/upgrade.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/demand-backup.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/scaling.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/version-service.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/affinity.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/scheduled-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/213/commits/a4aa728e147f6560f9b016ac093f04fa1b1d3b3f
image: `perconalab/percona-postgresql-operator:PR-213-a4aa728e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-213-a4aa728e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-213-a4aa728e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-213-a4aa728e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-213-a4aa728e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-213-a4aa728e-pgo-deployer`

**Review by tplavcic — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/init-deploy.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/affinity.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/demand-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/monitoring.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/scheduled-backup.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/ns-mode.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/smart-update.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-213/a4aa728e/version-service.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/213/commits/a4aa728e147f6560f9b016ac093f04fa1b1d3b3f
image: `perconalab/percona-postgresql-operator:PR-213-a4aa728e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-213-a4aa728e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-213-a4aa728e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-213-a4aa728e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-213-a4aa728e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-213-a4aa728e-pgo-deployer`

**Pull request merged**
