### PR TITLE
K8SPG-38 Test private repo usage

### PR DESCRIPTION
**Pull request by cap1984**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | failed |
| init-deploy | failed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/83/commits/f58b5b3fc391ff1ed6ab6d1fdd44783428f1ee3f
image: `perconalab/percona-postgresql-operator:PR-83-f58b5b3f-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-83-f58b5b3f-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-83-f58b5b3f-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-83-f58b5b3f-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-83-f58b5b3f-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-83-f58b5b3f-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| demand-backup | failed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/83/commits/1d683d62ab874c12ec722af8be6a9bd1473c156e
image: `perconalab/percona-postgresql-operator:PR-83-1d683d62-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-83-1d683d62-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-83-1d683d62-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-83-1d683d62-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-83-1d683d62-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-83-1d683d62-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| demand-backup | failed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/83/commits/1d683d62ab874c12ec722af8be6a9bd1473c156e
image: `perconalab/percona-postgresql-operator:PR-83-1d683d62-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-83-1d683d62-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-83-1d683d62-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-83-1d683d62-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-83-1d683d62-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-83-1d683d62-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| demand-backup | failed |
| data-migration-gcs | passed |
| scaling | failed |
| recreate | failed |
| affinity | failed |
| monitoring | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/83/commits/a4317a52ba2584b0f110855d749cc6276f9b7f98
image: `perconalab/percona-postgresql-operator:PR-83-a4317a52-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-83-a4317a52-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-83-a4317a52-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-83-a4317a52-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-83-a4317a52-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-83-a4317a52-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | failed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/83/commits/c9d225d3e2cad71df70b41a2e6c2f1e6e3179913
image: `perconalab/percona-postgresql-operator:PR-83-c9d225d3-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-83-c9d225d3-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-83-c9d225d3-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-83-c9d225d3-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-83-c9d225d3-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-83-c9d225d3-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-postgresql-operator/pull/83/commits/9b34a987f25bcaca4591445535fa0ea00bcb3c79
image: `perconalab/percona-postgresql-operator:PR-83-9b34a987-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-83-9b34a987-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-83-9b34a987-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-83-9b34a987-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-83-9b34a987-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-83-9b34a987-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/83/commits/ec759686753fded23d7445f1c50d37ce1c20f7cc
image: `perconalab/percona-postgresql-operator:PR-83-ec759686-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-83-ec759686-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-83-ec759686-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-83-ec759686-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-83-ec759686-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-83-ec759686-pgo-deployer`

**Review by hors — APPROVED** [review]

**Pull request merged**
