### PR TITLE
K8SPG-130 fix 'spec.pgPrimary.customconfig' option

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/136/commits/eef92b07c20859e4025ac0ef60f4bbfc4065903f
image: `perconalab/percona-postgresql-operator:PR-136-eef92b07-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-136-eef92b07-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-136-eef92b07-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-136-eef92b07-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-136-eef92b07-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-136-eef92b07-pgo-deployer`

**Review by qJkee — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/136/commits/ae8eb09d0b3fd7158f72cff0f5af95e0018f81f8
image: `perconalab/percona-postgresql-operator:PR-136-ae8eb09d-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-136-ae8eb09d-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-136-ae8eb09d-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-136-ae8eb09d-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-136-ae8eb09d-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-136-ae8eb09d-pgo-deployer`

**Review by cap1984 — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/136/commits/d88ed8e36babb0dbfada4823709b7c5750492d65
image: `perconalab/percona-postgresql-operator:PR-136-d88ed8e3-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-136-d88ed8e3-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-136-d88ed8e3-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-136-d88ed8e3-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-136-d88ed8e3-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-136-d88ed8e3-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| scheduled-backup | passed |
| tls-check | passed |
| upgrade | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/136/commits/99dc336cf1020adc41169cf22ebd4eb708f442c4
image: `perconalab/percona-postgresql-operator:PR-136-99dc336c-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-136-99dc336c-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-136-99dc336c-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-136-99dc336c-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-136-99dc336c-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-136-99dc336c-pgo-deployer`

**Pull request merged**
