### PR TITLE
CLOUD-660 public access to failed tests

### PR DESCRIPTION
**Pull request by nmarukovich**

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/demand-backup.log) |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/init-deploy.log) |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/upgrade.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/scheduled-backup.log) |
| scaling | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/scaling.log) |
| smart-update | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/smart-update.log) |
| recreate | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/recreate.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/version-service.log) |
| affinity | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/affinity.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/monitoring.log) |
| self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/self-healing.log) |
| operator-self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/operator-self-healing.log) |
| clone-cluster | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/clone-cluster.log) |
| tls-check | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/tls-check.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/users.log) |
| ns-mode | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/200/commits/acb7e60e3f4529b72938ecbc747bcdbf4fbe6c00
image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/upgrade.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/demand-backup.log) |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/init-deploy.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/scheduled-backup.log) |
| scaling | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/scaling.log) |
| smart-update | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/smart-update.log) |
| recreate | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/recreate.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/version-service.log) |
| affinity | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/affinity.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/monitoring.log) |
| self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/self-healing.log) |
| operator-self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/operator-self-healing.log) |
| clone-cluster | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/clone-cluster.log) |
| tls-check | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/tls-check.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/users.log) |
| ns-mode | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/200/commits/acb7e60e3f4529b72938ecbc747bcdbf4fbe6c00
image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-deployer`

**Review by cap1984 — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/upgrade.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/demand-backup.log) |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/init-deploy.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/scheduled-backup.log) |
| scaling | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/scaling.log) |
| smart-update | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/smart-update.log) |
| recreate | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/recreate.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/version-service.log) |
| affinity | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/affinity.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/monitoring.log) |
| self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/self-healing.log) |
| operator-self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/operator-self-healing.log) |
| clone-cluster | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/clone-cluster.log) |
| tls-check | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/tls-check.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/users.log) |
| ns-mode | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/200/commits/acb7e60e3f4529b72938ecbc747bcdbf4fbe6c00
image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/demand-backup.log) |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/upgrade.log) |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/init-deploy.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/scheduled-backup.log) |
| scaling | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/scaling.log) |
| smart-update | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/smart-update.log) |
| recreate | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/recreate.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/version-service.log) |
| affinity | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/affinity.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/monitoring.log) |
| self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/self-healing.log) |
| operator-self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/operator-self-healing.log) |
| clone-cluster | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/clone-cluster.log) |
| tls-check | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/tls-check.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/users.log) |
| ns-mode | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/200/commits/acb7e60e3f4529b72938ecbc747bcdbf4fbe6c00
image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/demand-backup.log) |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/upgrade.log) |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/init-deploy.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/scheduled-backup.log) |
| scaling | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/scaling.log) |
| smart-update | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/smart-update.log) |
| recreate | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/recreate.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/version-service.log) |
| affinity | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/affinity.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/monitoring.log) |
| self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/self-healing.log) |
| operator-self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/operator-self-healing.log) |
| clone-cluster | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/clone-cluster.log) |
| tls-check | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/tls-check.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/users.log) |
| ns-mode | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/200/commits/acb7e60e3f4529b72938ecbc747bcdbf4fbe6c00
image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-postgresql-operator/pull/200/commits/17e694c4373f49259ee0d2cf3f5b3bf338175884
image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/upgrade.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/demand-backup.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/init-deploy.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/scaling.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/version-service.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/affinity.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/scheduled-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/200/commits/17e694c4373f49259ee0d2cf3f5b3bf338175884
image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/upgrade.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/demand-backup.log) |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/init-deploy.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/scheduled-backup.log) |
| scaling | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/scaling.log) |
| smart-update | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/smart-update.log) |
| recreate | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/recreate.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/version-service.log) |
| affinity | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/affinity.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/monitoring.log) |
| self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/self-healing.log) |
| operator-self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/operator-self-healing.log) |
| clone-cluster | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/clone-cluster.log) |
| tls-check | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/tls-check.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/users.log) |
| ns-mode | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/acb7e60e/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/200/commits/acb7e60e3f4529b72938ecbc747bcdbf4fbe6c00
image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-200-acb7e60e-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-postgresql-operator/pull/200/commits/17e694c4373f49259ee0d2cf3f5b3bf338175884
image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/demand-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/upgrade.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/scheduled-backup.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/smart-update.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/version-service.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/init-deploy.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-200/17e694c4/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/200/commits/17e694c4373f49259ee0d2cf3f5b3bf338175884
image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-200-17e694c4-pgo-deployer`

**Pull request merged**
