### PR TITLE
K8SPG-101 Add scale to crd

### PR DESCRIPTION
**Pull request by nonemax**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | failed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | failed |
| upgrade | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/154/commits/ee52d7248b2a7a497685d2fcf1ea99a92b94c0a6
image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| scheduled-backup | passed |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | failed |
| data-migration-gcs | passed |
| upgrade | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/154/commits/ee52d7248b2a7a497685d2fcf1ea99a92b94c0a6
image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-postgresql-operator/pull/154/commits/ee52d7248b2a7a497685d2fcf1ea99a92b94c0a6
image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | failed |
| demand-backup | passed |
| scheduled-backup | passed |
| data-migration-gcs | passed |
| upgrade | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/154/commits/ee52d7248b2a7a497685d2fcf1ea99a92b94c0a6
image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| scheduled-backup | passed |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | failed |
| data-migration-gcs | passed |
| upgrade | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/154/commits/ee52d7248b2a7a497685d2fcf1ea99a92b94c0a6
image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-154-ee52d724-pgo-deployer`

**Review by hors — APPROVED** [review]

**Pull request merged**
