### PR TITLE
CLOUD-705 delete unused clusters

### PR DESCRIPTION
**Pull request by nmarukovich**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| We run 0 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/310/commits/f82eec1d94448a2013ebed3243e99192b74e689f
image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-deployer`

**Review by tplavcic — DISMISSED** [review]

**Review by hors — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/demand-backup.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/init-deploy.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/scheduled-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/upgrade.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/version-service.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/scaling.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/smart-update.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/f82eec1d/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/310/commits/f82eec1d94448a2013ebed3243e99192b74e689f
image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| We run 0 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/310/commits/f82eec1d94448a2013ebed3243e99192b74e689f
image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-310-f82eec1d-pgo-deployer`

**Review by tplavcic — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/cc4c391e/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/cc4c391e/smart-update.log) |
| We run 2 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/310/commits/cc4c391e04d83837c1e1f8f022f16d0c60cfb899
image: `perconalab/percona-postgresql-operator:PR-310-cc4c391e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-310-cc4c391e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-310-cc4c391e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-310-cc4c391e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-310-cc4c391e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-310-cc4c391e-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/cc4c391e/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-310/cc4c391e/smart-update.log) |
| We run 2 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/310/commits/cc4c391e04d83837c1e1f8f022f16d0c60cfb899
image: `perconalab/percona-postgresql-operator:PR-310-cc4c391e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-310-cc4c391e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-310-cc4c391e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-310-cc4c391e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-310-cc4c391e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-310-cc4c391e-pgo-deployer`

**Pull request merged**
