### PR TITLE
K8SPG-170 Get rid of crunchy native objects references

### PR DESCRIPTION
**Pull request by cap1984**

### CODE REVIEW

**Comment by cap1984** [comment]
We need to wait until @nonemax fix for pgbouncer user https://jira.percona.com/browse/K8SPG-172

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| upgrade | failed |
| init-deploy | passed |
| scaling | passed |
| smart-update | passed |
| recreate | failed |
| version-service | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| users | passed |
| ns-mode | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/197/commits/45060c6927dabd87b6e4e93113081dce5c308b90
image: `perconalab/percona-postgresql-operator:PR-197-45060c69-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-197-45060c69-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-197-45060c69-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-197-45060c69-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-197-45060c69-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-197-45060c69-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | failed |
| upgrade | failed |
| init-deploy | failed |
| smart-update | failed |
| scheduled-backup | failed |
| scaling | failed |
| version-service | failed |
| recreate | failed |
| affinity | failed |
| monitoring | failed |
| self-healing | failed |
| operator-self-healing | failed |
| clone-cluster | failed |
| tls-check | failed |
| users | failed |
| ns-mode | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/197/commits/bcdd311395e5878cb8c1947ff534b602b6937ff8
image: `perconalab/percona-postgresql-operator:PR-197-bcdd3113-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-197-bcdd3113-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-197-bcdd3113-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-197-bcdd3113-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-197-bcdd3113-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-197-bcdd3113-pgo-deployer`

**Review by nonemax — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| upgrade | failed |
| init-deploy | passed |
| smart-update | passed |
| scaling | passed |
| version-service | passed |
| recreate | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| users | passed |
| ns-mode | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/197/commits/e0b0a9440631b59a87e5c3fa0e489f2d4a3e0885
image: `perconalab/percona-postgresql-operator:PR-197-e0b0a944-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-197-e0b0a944-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-197-e0b0a944-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-197-e0b0a944-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-197-e0b0a944-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-197-e0b0a944-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| upgrade | passed |
| smart-update | passed |
| version-service | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| users | passed |
| ns-mode | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/197/commits/df4f1db0eb0310076c4c060a6a26a8c830d056f1
image: `perconalab/percona-postgresql-operator:PR-197-df4f1db0-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-197-df4f1db0-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-197-df4f1db0-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-197-df4f1db0-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-197-df4f1db0-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-197-df4f1db0-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| upgrade | passed |
| demand-backup | passed |
| smart-update | passed |
| scaling | passed |
| version-service | passed |
| recreate | passed |
| scheduled-backup | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| users | passed |
| ns-mode | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/197/commits/673230789cbb27f17081f4ee0175d2ad049e29c1
image: `perconalab/percona-postgresql-operator:PR-197-67323078-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-197-67323078-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-197-67323078-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-197-67323078-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-197-67323078-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-197-67323078-pgo-deployer`

**Pull request merged**
