### PR TITLE
K8SPG-143 K8S 1.22 preparation

### PR DESCRIPTION
**Pull request by cap1984**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | failed |
| init-deploy | failed |
| data-migration-gcs | passed |
| scaling | failed |
| recreate | failed |
| affinity | failed |
| monitoring | failed |
| scheduled-backup | failed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | failed |
| tls-check | passed |
| upgrade | failed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/8eb5e130ca2ebd29bca92d90697d71399359c865
image: `perconalab/percona-postgresql-operator:PR-158-8eb5e130-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-8eb5e130-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-8eb5e130-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-8eb5e130-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-8eb5e130-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-8eb5e130-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | failed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/2af41aebb071b8c103b24539eea56094a920efb4
image: `perconalab/percona-postgresql-operator:PR-158-2af41aeb-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-2af41aeb-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-2af41aeb-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-2af41aeb-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-2af41aeb-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-2af41aeb-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/94b976296387cbe6228cf0ac171d0a9f92e45bd0
image: `perconalab/percona-postgresql-operator:PR-158-94b97629-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-94b97629-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-94b97629-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-94b97629-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-94b97629-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-94b97629-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/fd46694f376d3d5c4bc4de76ead5ab7c0cc319d2
image: `perconalab/percona-postgresql-operator:PR-158-fd46694f-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-fd46694f-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-fd46694f-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-fd46694f-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-fd46694f-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-fd46694f-pgo-deployer`

**Review by hors — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | failed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/b3acf61106f782b09c32d4d2ae9696a3ee934b5e
image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| scheduled-backup | failed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| users | passed |
| data-migration-gcs | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/b3acf61106f782b09c32d4d2ae9696a3ee934b5e
image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-deployer`

**Review by nonemax — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| scaling | passed |
| scheduled-backup | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| users | passed |
| data-migration-gcs | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/b3acf61106f782b09c32d4d2ae9696a3ee934b5e
image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-b3acf611-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | failed |
| scheduled-backup | failed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | failed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/b8823cfb0293801c99abcc2a0facca5410c71d1d
image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/b8823cfb0293801c99abcc2a0facca5410c71d1d
image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | failed |
| demand-backup | passed |
| scheduled-backup | failed |
| data-migration-gcs | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | failed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/b8823cfb0293801c99abcc2a0facca5410c71d1d
image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-b8823cfb-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | failed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/981984c53274211f0c9fd441f3704d7abe5ab347
image: `perconalab/percona-postgresql-operator:PR-158-981984c5-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-981984c5-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-981984c5-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-981984c5-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-981984c5-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-981984c5-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| scheduled-backup | failed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | failed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/0ec1043f376e6a08f0fdead0e0dceaea99eb3098
image: `perconalab/percona-postgresql-operator:PR-158-0ec1043f-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-0ec1043f-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-0ec1043f-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-0ec1043f-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-0ec1043f-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-0ec1043f-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | failed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/9305862ce2abc73bc9bc7b97f2c1439488ae82dc
image: `perconalab/percona-postgresql-operator:PR-158-9305862c-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-9305862c-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-9305862c-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-9305862c-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-9305862c-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-9305862c-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/3d4a8a46c230ea18909d3bb8dabe65681b5e0722
image: `perconalab/percona-postgresql-operator:PR-158-3d4a8a46-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-3d4a8a46-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-3d4a8a46-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-3d4a8a46-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-3d4a8a46-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-3d4a8a46-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/3aea587a10693e460462c07d9e7220e1923bff21
image: `perconalab/percona-postgresql-operator:PR-158-3aea587a-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-3aea587a-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-3aea587a-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-3aea587a-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-3aea587a-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-3aea587a-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/4b39898e9b1aac595380b6f2b8276baccf1ed77e
image: `perconalab/percona-postgresql-operator:PR-158-4b39898e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-4b39898e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-4b39898e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-4b39898e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-4b39898e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-4b39898e-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/158/commits/36b34daede4c41bde29b06a0d5e780ebd4e9fe5b
image: `perconalab/percona-postgresql-operator:PR-158-36b34dae-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-158-36b34dae-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-158-36b34dae-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-158-36b34dae-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-158-36b34dae-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-158-36b34dae-pgo-deployer`

**Pull request merged**
