### PR TITLE
K8SPG-64 Test compliance with Openshift 4

### PR DESCRIPTION
**Pull request by cap1984**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/70/commits/b2e7c0097bac23b77c79efd423b44cb307f6238f
image: `perconalab/percona-postgresql-operator:PR-70-b2e7c009-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-70-b2e7c009-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-70-b2e7c009-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-70-b2e7c009-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-70-b2e7c009-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-70-b2e7c009-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/70/commits/3a95e220950c154ec08772db5200650fa520a0a3
image: `perconalab/percona-postgresql-operator:PR-70-3a95e220-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-70-3a95e220-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-70-3a95e220-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-70-3a95e220-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-70-3a95e220-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-70-3a95e220-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/70/commits/e297d7b3d302870a77995c26ffa32893aff4792a
image: `perconalab/percona-postgresql-operator:PR-70-e297d7b3-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-70-e297d7b3-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-70-e297d7b3-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-70-e297d7b3-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-70-e297d7b3-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-70-e297d7b3-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| affinity | passed |
| demand-backup | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/70/commits/e297d7b3d302870a77995c26ffa32893aff4792a
image: `perconalab/percona-postgresql-operator:PR-70-e297d7b3-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-70-e297d7b3-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-70-e297d7b3-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-70-e297d7b3-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-70-e297d7b3-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-70-e297d7b3-pgo-deployer`

**Review by hors — APPROVED** [review]

**Pull request merged**
