### PR TITLE
K8SPG-116: Fix scheduled-backup test

### PR DESCRIPTION
**Pull request by egegunes**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3883836e/scheduled-backup.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/214/commits/3883836e69e572bae14b6bf717cb8e4ae5bc3f7b
image: `perconalab/percona-postgresql-operator:PR-214-3883836e-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-214-3883836e-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-214-3883836e-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-214-3883836e-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-214-3883836e-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-214-3883836e-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/43c859e3/scheduled-backup.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/214/commits/43c859e3602aa1b308f0e2ea9b446ea6357900f7
image: `perconalab/percona-postgresql-operator:PR-214-43c859e3-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-214-43c859e3-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-214-43c859e3-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-214-43c859e3-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-214-43c859e3-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-214-43c859e3-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/upgrade.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/demand-backup.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/scaling.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/version-service.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/recreate.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/scheduled-backup.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/214/commits/3bf1fdcb3523c80046cc6244ef1655089afde225
image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/smart-update.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/version-service.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/scheduled-backup.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/init-deploy.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/214/commits/3bf1fdcb3523c80046cc6244ef1655089afde225
image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/smart-update.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/version-service.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/scheduled-backup.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-214/3bf1fdcb/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/214/commits/3bf1fdcb3523c80046cc6244ef1655089afde225
image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-214-3bf1fdcb-pgo-deployer`

**Review by cap1984 — APPROVED** [review]

**Review by hors — APPROVED** [review]

**Pull request merged**
