### PR TITLE
K8SPG-80 rename percona CR

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | failed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/74/commits/b82c4828052d134c5a41d9231e4ec727a2f118f4
image: `perconalab/percona-postgresql-operator:PR-74-b82c4828-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-74-b82c4828-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-74-b82c4828-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-74-b82c4828-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-74-b82c4828-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-74-b82c4828-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | failed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/74/commits/7a700e000a50fcb0082204a66b7a5c3182b23a43
image: `perconalab/percona-postgresql-operator:PR-74-7a700e00-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-74-7a700e00-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-74-7a700e00-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-74-7a700e00-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-74-7a700e00-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-74-7a700e00-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| demand-backup | failed |
| data-migration-gcs | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/74/commits/7a700e000a50fcb0082204a66b7a5c3182b23a43
image: `perconalab/percona-postgresql-operator:PR-74-7a700e00-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-74-7a700e00-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-74-7a700e00-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-74-7a700e00-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-74-7a700e00-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-74-7a700e00-pgo-deployer`

**Review by nonemax — APPROVED** [review]

**Review by cap1984 — APPROVED** [review]
lgtm

**Pull request merged**
