### PR TITLE
K8SPG-152 add 'perconapgclusters' resource to target role

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/182/commits/05e0a8ea84bfc0804d74f78f3d94b05adbf47827
image: `perconalab/percona-postgresql-operator:PR-182-05e0a8ea-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-182-05e0a8ea-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-182-05e0a8ea-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-182-05e0a8ea-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-182-05e0a8ea-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-182-05e0a8ea-pgo-deployer`

**Review by cap1984 — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | failed |
| smart-update | passed |
| version-service | passed |
| users | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/182/commits/d675d6184eb485cf89bd75dadb0e08f46606d3e9
image: `perconalab/percona-postgresql-operator:PR-182-d675d618-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-182-d675d618-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-182-d675d618-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-182-d675d618-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-182-d675d618-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-182-d675d618-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| scheduled-backup | passed |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | failed |
| data-migration-gcs | passed |
| smart-update | passed |
| version-service | passed |
| users | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/182/commits/d675d6184eb485cf89bd75dadb0e08f46606d3e9
image: `perconalab/percona-postgresql-operator:PR-182-d675d618-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-182-d675d618-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-182-d675d618-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-182-d675d618-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-182-d675d618-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-182-d675d618-pgo-deployer`

**Review by egegunes — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | failed |
| smart-update | passed |
| version-service | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/182/commits/5b09a974b6228decd30c2e8e94a207b07ccf4ce2
image: `perconalab/percona-postgresql-operator:PR-182-5b09a974-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-182-5b09a974-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-182-5b09a974-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-182-5b09a974-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-182-5b09a974-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-182-5b09a974-pgo-deployer`

**Pull request merged**
