### PR TITLE
K8SPG-193 Add checks for Pgreplicas object

### PR DESCRIPTION
**Pull request by nonemax**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/upgrade.log) |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/init-deploy.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/demand-backup.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/scheduled-backup.log) |
| scaling | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/scaling.log) |
| smart-update | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/smart-update.log) |
| recreate | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/recreate.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/version-service.log) |
| affinity | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/affinity.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/monitoring.log) |
| self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/self-healing.log) |
| operator-self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/operator-self-healing.log) |
| clone-cluster | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/clone-cluster.log) |
| tls-check | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/tls-check.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/users.log) |
| ns-mode | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/272/commits/9f12feead5ce1497a2c75113d39088f92bead1c4
image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-deployer`

**Review by egegunes — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/demand-backup.log) |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/upgrade.log) |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/init-deploy.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/scheduled-backup.log) |
| scaling | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/scaling.log) |
| smart-update | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/smart-update.log) |
| recreate | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/recreate.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/version-service.log) |
| affinity | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/affinity.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/monitoring.log) |
| self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/self-healing.log) |
| operator-self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/operator-self-healing.log) |
| clone-cluster | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/clone-cluster.log) |
| tls-check | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/tls-check.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/users.log) |
| ns-mode | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/272/commits/9f12feead5ce1497a2c75113d39088f92bead1c4
image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/demand-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/upgrade.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/init-deploy.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/scaling.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/version-service.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/recreate.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/scheduled-backup.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/272/commits/9f12feead5ce1497a2c75113d39088f92bead1c4
image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/init-deploy.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/upgrade.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/scaling.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/smart-update.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/recreate.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/version-service.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/demand-backup.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/affinity.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/scheduled-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-272/9f12feea/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/272/commits/9f12feead5ce1497a2c75113d39088f92bead1c4
image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-272-9f12feea-pgo-deployer`

**Review by inelpandzic — APPROVED** [review]

**Review by cap1984 — APPROVED** [review]

**Pull request merged**
