### PR TITLE
K8SPG-145 Remove service annotations

### PR DESCRIPTION
**Pull request by cap1984**
Since EKS does not provide any annotations for service objects
we are to remove them from compare files

### CODE REVIEW

**Review by hors — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | failed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/172/commits/9df64958d6963e9760ad34a5a87634696f88edc0
image: `perconalab/percona-postgresql-operator:PR-172-9df64958-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-172-9df64958-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-172-9df64958-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-172-9df64958-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-172-9df64958-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-172-9df64958-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/172/commits/bb7bb36c8bf2381acecf26af6b9f280be543dade
image: `perconalab/percona-postgresql-operator:PR-172-bb7bb36c-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-172-bb7bb36c-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-172-bb7bb36c-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-172-bb7bb36c-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-172-bb7bb36c-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-172-bb7bb36c-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| self-healing | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/172/commits/a8be1b3b80ed9c6b575c813013fd5c8112b4d406
image: `perconalab/percona-postgresql-operator:PR-172-a8be1b3b-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-172-a8be1b3b-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-172-a8be1b3b-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-172-a8be1b3b-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-172-a8be1b3b-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-172-a8be1b3b-pgo-deployer`

**Comment by danielbichuetti** [comment]
Hi, since service annotations are one way to use other tools that handle with external DNS, certificates and so on, isn't better to keep annotations ?  

Crunchydata Operator allows setting custom annotations on service, Elasticsearch and so on. It's a common behavior to make usage of custom annotations.

**Pull request merged**
