### PR TITLE
K8SPG-293 Move ansible-galaxy install to build time

### PR DESCRIPTION
**Pull request by dforste**
Moving the ansible install to build time. 

Installing things at runtime are bad and break on air gapped clusters.

### CODE REVIEW

**Review by cap1984 — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/demand-backup.log) |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/upgrade.log) |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/init-deploy.log) |
| scaling | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/scaling.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/scheduled-backup.log) |
| smart-update | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/smart-update.log) |
| recreate | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/recreate.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/version-service.log) |
| affinity | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/affinity.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/monitoring.log) |
| self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/self-healing.log) |
| operator-self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/operator-self-healing.log) |
| clone-cluster | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/clone-cluster.log) |
| tls-check | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/tls-check.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/users.log) |
| ns-mode | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/268/commits/c5766da5536a66a2e7126bdc9fde84d98325346c
image: `perconalab/percona-postgresql-operator:PR-268-c5766da5-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-268-c5766da5-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-268-c5766da5-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-268-c5766da5-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-268-c5766da5-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-268-c5766da5-pgo-deployer`

**Review by hors — CHANGES_REQUESTED** [review]
It does not work. Please recheck your code

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/init-deploy.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/demand-backup.log) |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/upgrade.log) |
| scaling | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/scaling.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/scheduled-backup.log) |
| smart-update | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/smart-update.log) |
| recreate | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/recreate.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/version-service.log) |
| affinity | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/affinity.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/monitoring.log) |
| self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/self-healing.log) |
| operator-self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/operator-self-healing.log) |
| clone-cluster | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/clone-cluster.log) |
| tls-check | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/tls-check.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/users.log) |
| ns-mode | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-268/c5766da5/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/268/commits/c5766da5536a66a2e7126bdc9fde84d98325346c
image: `perconalab/percona-postgresql-operator:PR-268-c5766da5-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-268-c5766da5-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-268-c5766da5-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-268-c5766da5-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-268-c5766da5-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-268-c5766da5-pgo-deployer`

**Comment by cap1984** [comment]
https://jira.percona.com/browse/K8SPG-293

**Review by cap1984 — APPROVED** [review]

**Review by tplavcic — APPROVED** [review]

**Review by hors — APPROVED** [review]

**Pull request merged**
