### PR TITLE
K8SPG-38 Demand backup rebased

### PR DESCRIPTION
**Pull request by cap1984**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/55/commits/ad44c8049d36caf10756c1b3097a40aa26fb7f59
image: `perconalab/percona-postgresql-operator:PR-55-ad44c804-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-55-ad44c804-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-55-ad44c804-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-55-ad44c804-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-55-ad44c804-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-55-ad44c804-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/55/commits/f91baf8f5a50619c5419b05a4527f0da43a6da9b
image: `perconalab/percona-postgresql-operator:PR-55-f91baf8f-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-55-f91baf8f-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-55-f91baf8f-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-55-f91baf8f-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-55-f91baf8f-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-55-f91baf8f-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| demand-backup | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/55/commits/f91baf8f5a50619c5419b05a4527f0da43a6da9b
image: `perconalab/percona-postgresql-operator:PR-55-f91baf8f-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-55-f91baf8f-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-55-f91baf8f-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-55-f91baf8f-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-55-f91baf8f-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-55-f91baf8f-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | failed |
| affinity | failed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/55/commits/9fc86070d53e7528b71d334fe35f745ede07f3a3
image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/55/commits/9fc86070d53e7528b71d334fe35f745ede07f3a3
image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| demand-backup | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/55/commits/9fc86070d53e7528b71d334fe35f745ede07f3a3
image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-55-9fc86070-pgo-deployer`

**Review by hors — APPROVED** [review]

**Pull request merged**
