### PR TITLE
K8SPG-120 keep backups and PVC by default

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| demand-backup | failed |
| data-migration-gcs | passed |
| scaling | failed |
| recreate | failed |
| affinity | failed |
| monitoring | passed |
| scheduled-backup | failed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/153/commits/ff3b63894af3b41281c855eb4958a2a796299051
image: `perconalab/percona-postgresql-operator:PR-153-ff3b6389-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-153-ff3b6389-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-153-ff3b6389-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-153-ff3b6389-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-153-ff3b6389-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-153-ff3b6389-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | failed |
| init-deploy | failed |
| data-migration-gcs | passed |
| scaling | failed |
| recreate | failed |
| affinity | failed |
| monitoring | passed |
| scheduled-backup | failed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/153/commits/25fa1fb54d34725542ca71c6bede146600f73f17
image: `perconalab/percona-postgresql-operator:PR-153-25fa1fb5-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-153-25fa1fb5-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-153-25fa1fb5-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-153-25fa1fb5-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-153-25fa1fb5-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-153-25fa1fb5-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | failed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | failed |
| upgrade | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/153/commits/83673b77c657e37e737fe46d5d120754d91959c5
image: `perconalab/percona-postgresql-operator:PR-153-83673b77-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-153-83673b77-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-153-83673b77-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-153-83673b77-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-153-83673b77-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-153-83673b77-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| data-migration-gcs | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/153/commits/f36863108ad0ab542d79529e286f9c6491d46715
image: `perconalab/percona-postgresql-operator:PR-153-f3686310-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-153-f3686310-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-153-f3686310-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-153-f3686310-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-153-f3686310-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-153-f3686310-pgo-deployer`

**Pull request merged**
