### PR TITLE
K8SPG-145 Use next operator version in main

### PR DESCRIPTION
**Pull request by cap1984**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| demand-backup | passed |
| scaling | failed |
| recreate | passed |
| affinity | failed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/180/commits/fdb5a62ba1b46ebbcd2b947c43fbbb48f7d3deb0
image: `perconalab/percona-postgresql-operator:PR-180-fdb5a62b-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-180-fdb5a62b-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-180-fdb5a62b-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-180-fdb5a62b-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-180-fdb5a62b-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-180-fdb5a62b-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | failed |
| smart-update | passed |
| version-service | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/180/commits/9093b64cc1a999c43d93f3a06eae638eec3ddc58
image: `perconalab/percona-postgresql-operator:PR-180-9093b64c-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-180-9093b64c-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-180-9093b64c-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-180-9093b64c-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-180-9093b64c-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-180-9093b64c-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/180/commits/2ae20ad54d2b8c134652756d1f7c478c1c551ffd
image: `perconalab/percona-postgresql-operator:PR-180-2ae20ad5-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-180-2ae20ad5-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-180-2ae20ad5-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-180-2ae20ad5-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-180-2ae20ad5-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-180-2ae20ad5-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| scaling | passed |
| recreate | passed |
| affinity | passed |
| monitoring | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| upgrade | failed |
| smart-update | passed |
| version-service | passed |
| users | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/180/commits/3391219347cb599257b92467b2736543b3209fe9
image: `perconalab/percona-postgresql-operator:PR-180-33912193-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-180-33912193-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-180-33912193-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-180-33912193-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-180-33912193-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-180-33912193-pgo-deployer`

**Review by hors — APPROVED** [review]

**Pull request merged**
