### PR TITLE
K8SPG-148 Fix backrest repo imagePullPolicy update

### PR DESCRIPTION
**Pull request by nonemax**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | passed |
| init-deploy | passed |
| upgrade | passed |
| scaling | passed |
| smart-update | passed |
| recreate | passed |
| version-service | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| users | passed |
| ns-mode | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/188/commits/cad89d2653243769ce1571904c214f1613c06fdb
image: `perconalab/percona-postgresql-operator:PR-188-cad89d26-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-188-cad89d26-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-188-cad89d26-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-188-cad89d26-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-188-cad89d26-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-188-cad89d26-pgo-deployer`

**Comment by cap1984** [comment]
pls try enabling pgbadger with non default imagepullpolicy

**Review by hors — COMMENTED** [review]
@nonemax @cap1984  I think we need to have test for it. But please do not create separate test just add additional test case e.g. for init test. Create the cluster with default `imagePullPolicy` for all images  and then change it to e.g. `Always` and check the results.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| demand-backup | passed |
| upgrade | passed |
| smart-update | passed |
| scaling | passed |
| version-service | passed |
| recreate | passed |
| affinity | passed |
| scheduled-backup | passed |
| monitoring | passed |
| self-healing | passed |
| operator-self-healing | passed |
| clone-cluster | passed |
| tls-check | passed |
| users | passed |
| ns-mode | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/188/commits/762e0bed2003612e3bbc108455a3935e09a1d657
image: `perconalab/percona-postgresql-operator:PR-188-762e0bed-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-188-762e0bed-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-188-762e0bed-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-188-762e0bed-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-188-762e0bed-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-188-762e0bed-pgo-deployer`

**Review by cap1984 — APPROVED** [review]
LGTM

**Review by hors — APPROVED** [review]

**Pull request merged**
