### PR TITLE
CLOUD-695 jenkinsfile improvements

### PR DESCRIPTION
**Pull request by nmarukovich**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/demand-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/upgrade.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/init-deploy.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/scaling.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/smart-update.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/recreate.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/version-service.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/scheduled-backup.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/79e7028a/ns-mode.log) |
| We run 16 out of 20|

commit: https://github.com/percona/percona-postgresql-operator/pull/247/commits/79e7028a268189e2f5de6905cc3a0aac9a9f837e
image: `perconalab/percona-postgresql-operator:PR-247-79e7028a-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-247-79e7028a-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-247-79e7028a-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-247-79e7028a-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-247-79e7028a-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-247-79e7028a-pgo-deployer`

**Review by tplavcic — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/demand-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/upgrade.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/scaling.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/smart-update.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/recreate.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/version-service.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/scheduled-backup.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/ns-mode.log) |
| We run 16 out of 19|

commit: https://github.com/percona/percona-postgresql-operator/pull/247/commits/bfe80f5b670967c9097f85edb9956512a7669304
image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/demand-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/upgrade.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/scheduled-backup.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/smart-update.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/version-service.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/init-deploy.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/ns-mode.log) |
| We run 16 out of 19|

commit: https://github.com/percona/percona-postgresql-operator/pull/247/commits/bfe80f5b670967c9097f85edb9956512a7669304
image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/demand-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/upgrade.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/init-deploy.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/scheduled-backup.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/recreate.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/version-service.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/bfe80f5b/ns-mode.log) |
| We run 16 out of 18|

commit: https://github.com/percona/percona-postgresql-operator/pull/247/commits/bfe80f5b670967c9097f85edb9956512a7669304
image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-247-bfe80f5b-pgo-deployer`

**Review by cap1984 — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/demand-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/scaling.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/version-service.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/affinity.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/scheduled-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/cd56de3c/ns-mode.log) |
| We run 16 out of 17|

commit: https://github.com/percona/percona-postgresql-operator/pull/247/commits/cd56de3cabdd8a8322b5bad6f93dc88fa8fe7f60
image: `perconalab/percona-postgresql-operator:PR-247-cd56de3c-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-247-cd56de3c-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-247-cd56de3c-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-247-cd56de3c-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-247-cd56de3c-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-247-cd56de3c-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/demand-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/scaling.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/version-service.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/affinity.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/scheduled-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/6d34b127/ns-mode.log) |
| We run 16 out of 17|

commit: https://github.com/percona/percona-postgresql-operator/pull/247/commits/6d34b127ff39aaf655eacb7f5a37f7bd55cf2e09
image: `perconalab/percona-postgresql-operator:PR-247-6d34b127-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-247-6d34b127-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-247-6d34b127-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-247-6d34b127-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-247-6d34b127-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-247-6d34b127-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| We run 0 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/247/commits/6933b8bcf2e06b9cfe1a32512a90c05e2caaad40
image: `perconalab/percona-postgresql-operator:PR-247-6933b8bc-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-247-6933b8bc-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-247-6933b8bc-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-247-6933b8bc-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-247-6933b8bc-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-247-6933b8bc-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| We run 0 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/247/commits/00715370ccdc1844eb73e62605a445fdad968ab3
image: `perconalab/percona-postgresql-operator:PR-247-00715370-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-247-00715370-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-247-00715370-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-247-00715370-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-247-00715370-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-247-00715370-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/demand-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/scaling.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/version-service.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/affinity.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/scheduled-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-247/00715370/ns-mode.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-postgresql-operator/pull/247/commits/00715370ccdc1844eb73e62605a445fdad968ab3
image: `perconalab/percona-postgresql-operator:PR-247-00715370-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-247-00715370-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-247-00715370-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-247-00715370-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-247-00715370-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-247-00715370-pgo-deployer`

**Pull request merged**
