### PR TITLE
K8SPG-202 update go version to 1.18

### PR DESCRIPTION
**Pull request by hors**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-postgresql-operator/pull/250/commits/ef091d9c3008747164696fc3755067aad96e08dd
image: `perconalab/percona-postgresql-operator:PR-250-ef091d9c-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-250-ef091d9c-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-250-ef091d9c-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-250-ef091d9c-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-250-ef091d9c-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-250-ef091d9c-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/demand-backup.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/init-deploy.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/smart-update.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/scaling.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/version-service.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/tls-check.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/scheduled-backup.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/4653db4b/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/250/commits/4653db4b670367e928ecc489c12cc12b14c3ef73
image: `perconalab/percona-postgresql-operator:PR-250-4653db4b-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-250-4653db4b-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-250-4653db4b-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-250-4653db4b-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-250-4653db4b-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-250-4653db4b-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/demand-backup.log) |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/init-deploy.log) |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/upgrade.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/scheduled-backup.log) |
| scaling | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/scaling.log) |
| smart-update | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/smart-update.log) |
| recreate | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/recreate.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/version-service.log) |
| affinity | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/affinity.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/monitoring.log) |
| self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/self-healing.log) |
| operator-self-healing | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/operator-self-healing.log) |
| clone-cluster | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/clone-cluster.log) |
| tls-check | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/tls-check.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/users.log) |
| ns-mode | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/250/commits/b8480c9ff20600ebd40e6a1fd04d05609d9c0113
image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/init-deploy.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/demand-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/upgrade.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/scaling.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/smart-update.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/version-service.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/affinity.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/scheduled-backup.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/250/commits/b8480c9ff20600ebd40e6a1fd04d05609d9c0113
image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/demand-backup.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/scheduled-backup.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/upgrade.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/smart-update.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/version-service.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/init-deploy.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/scaling.log) |
| recreate | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/recreate.log) |
| affinity | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/affinity.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/monitoring.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/self-healing.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/operator-self-healing.log) |
| clone-cluster | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/clone-cluster.log) |
| tls-check | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/tls-check.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/users.log) |
| ns-mode | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-pg-operator/PR-250/b8480c9f/ns-mode.log) |

commit: https://github.com/percona/percona-postgresql-operator/pull/250/commits/b8480c9ff20600ebd40e6a1fd04d05609d9c0113
image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-250-b8480c9f-pgo-deployer`

**Review by egegunes — APPROVED** [review]

**Pull request merged**
