### PR TITLE
K8SPG-38 Demand backup test

### PR DESCRIPTION
**Pull request by cap1984**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/e501e4d4e46aedfa6f45e6703217ee4f001b5587
image: `perconalab/percona-postgresql-operator:PR-44-e501e4d4-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-e501e4d4-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-e501e4d4-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-e501e4d4-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-e501e4d4-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-e501e4d4-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | failed |
| recreate | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/9cd0d642e44ab456f402487469bd830e448cf069
image: `perconalab/percona-postgresql-operator:PR-44-9cd0d642-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-9cd0d642-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-9cd0d642-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-9cd0d642-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-9cd0d642-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-9cd0d642-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | failed |
| recreate | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/c34594e5c54665207a1042c5fe94824b8cf49c9a
image: `perconalab/percona-postgresql-operator:PR-44-c34594e5-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-c34594e5-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-c34594e5-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-c34594e5-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-c34594e5-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-c34594e5-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/db114ea99cc745f8aabdd0689cdf5f391e970a7c
image: `perconalab/percona-postgresql-operator:PR-44-db114ea9-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-db114ea9-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-db114ea9-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-db114ea9-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-db114ea9-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-db114ea9-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/e6fb57253c4b27900072c4094972c20fe2efb422
image: `perconalab/percona-postgresql-operator:PR-44-e6fb5725-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-e6fb5725-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-e6fb5725-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-e6fb5725-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-e6fb5725-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-e6fb5725-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/e7bb08b491b810f1d572e86ed1310fe7eadd8643
image: `perconalab/percona-postgresql-operator:PR-44-e7bb08b4-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-e7bb08b4-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-e7bb08b4-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-e7bb08b4-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-e7bb08b4-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-e7bb08b4-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/e7bb08b491b810f1d572e86ed1310fe7eadd8643
image: `perconalab/percona-postgresql-operator:PR-44-e7bb08b4-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-e7bb08b4-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-e7bb08b4-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-e7bb08b4-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-e7bb08b4-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-e7bb08b4-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/06d68f3cc3b2b457f9430a90da663d00d2cb2738
image: `perconalab/percona-postgresql-operator:PR-44-06d68f3c-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-06d68f3c-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-06d68f3c-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-06d68f3c-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-06d68f3c-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-06d68f3c-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/06d68f3cc3b2b457f9430a90da663d00d2cb2738
image: `perconalab/percona-postgresql-operator:PR-44-06d68f3c-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-06d68f3c-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-06d68f3c-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-06d68f3c-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-06d68f3c-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-06d68f3c-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/47f53b0a18dd115bcf9480288cded9da53e9cacf
image: `perconalab/percona-postgresql-operator:PR-44-47f53b0a-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-47f53b0a-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-47f53b0a-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-47f53b0a-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-47f53b0a-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-47f53b0a-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/6f470810eceda2fcdea9b260b57423cc312a99ab
image: `perconalab/percona-postgresql-operator:PR-44-6f470810-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-6f470810-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-6f470810-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-6f470810-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-6f470810-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-6f470810-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/6f470810eceda2fcdea9b260b57423cc312a99ab
image: `perconalab/percona-postgresql-operator:PR-44-6f470810-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-6f470810-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-6f470810-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-6f470810-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-6f470810-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-6f470810-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/15330622b27772d3a090e750eec9634e3f56a385
image: `perconalab/percona-postgresql-operator:PR-44-15330622-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-15330622-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-15330622-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-15330622-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-15330622-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-15330622-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| demand-backup | failed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/1b7a9264734d5adda07aacdab6074876eb507c73
image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| demand-backup | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/1b7a9264734d5adda07aacdab6074876eb507c73
image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-deployer`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| scaling | passed |
| recreate | passed |
| demand-backup | passed |

commit: https://github.com/percona/percona-postgresql-operator/pull/44/commits/1b7a9264734d5adda07aacdab6074876eb507c73
image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-apiserver`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-event`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-rmdata`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-scheduler`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-postgres-operator`

image: `perconalab/percona-postgresql-operator:PR-44-1b7a9264-pgo-deployer`

**Review by hors — APPROVED** [review]

**Pull request closed without merging**
